# Generated by Django 6.0.4 on 2026-05-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'enrollment', 'verbose_name_plural': '05- enrollments'},
        ),
        migrations.AlterModelOptions(
            name='lessonactivity',
            options={'verbose_name': 'lesson activity', 'verbose_name_plural': '03- lesson activities'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': '04- topics'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
